// ‼️ This file is autogenerated by InterfaceLogger.AOT
namespace InterfaceLoggerTests.Data
{
    public partial class SingleDemoLoggerFactory
    {
        public partial IExampleLogger GetExampleLogger()
            => new Generated_IExampleLogger();

        public class Generated_IExampleLogger : InterfaceLogger.AotLogger<IExampleLogger>, IExampleLogger
        {
            public void Example()
                => base.Log(this, "Example");
        }
    }
}
